//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CallNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallNote()
        {
            this.CallNote1 = new HashSet<CallNote>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int customer_id { get; set; }
        [Display(Name = "Content")]
        public string text_content { get; set; }
        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> date_created { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallNote> CallNote1 { get; set; }
        public virtual CallNote CallNote2 { get; set; }
        public override string ToString()
        {
            return string.Format("call note => id:{0}, parent_id:{1}, text_content:{2}, date_created:{3}",id,customer_id, text_content, date_created);
        }
    }
}
