//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CallNotes = new HashSet<CallNote>();
        }
        
        public int id { get; set; }
        [Display(Name = "Username")]
        [Required]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Username must between 5 and 20 characters")]
        [RegularExpression(@"^[a-zA-Z0-9]*$", ErrorMessage = "Username must contains only letter or number")]
        public string username { get; set; }
        [Display(Name = "First Name")]
        [Required]
        public string first_name { get; set; }
        [Display(Name = "Last Name")]
        [Required]
        [RegularExpression(@"^[a-zA-Z]*$", ErrorMessage = "Last name must contains only letter")]
        public string last_name { get; set; }
        [Display(Name = "Phone Number")]
        [Required]
        public string phone_number { get; set; }
        [Display(Name = "Date of Birth")]
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime date_of_birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallNote> CallNotes { get; set; }
        public override string ToString()
        {
            return string.Format("customer => id:{0}, username:{1}, first_name:{2}, last_name:{3}, phone_number:{4}, date_of_birth{5}", id, username, first_name, last_name, phone_number, date_of_birth);
        }
    }
}

